version: "3.8"
services:
  front:
    build: ./front
    networks:
      - osint
  back:
    build: "./back"
    volumes:
      - ./data:/SpyScrap/src/data
    networks:
      - osint

  reverse-proxy:
    container_name: reverse-proxy
    build: reverse-proxy
    ports:
      - "80:80"
    networks:
      - osint
    depends_on:
      - back
      - front
networks:
  osint:
