version: "3.8"
services:
  front:
    build: ./front
    ports:
      - "80:8080"
    networks:
      - osint
  back:
    build: "./back"
    ports:
      - "5000:5000"
    volumes:
      - ./data:/SpyScrap/src/data
    networks:
      - osint
networks:
  osint:
